# Title of your site
title = "R Markdown"

# The URL of your site.
# End your URL with a `/` trailing slash, e.g. `https://example.com/`.
baseurl = "/"

# Name the theme folder in `themes/`.
theme = "hugo-graphite"

# Enable analytics by entering your Google Analytics tracking ID
googleAnalytics = ""

relativeurls = false
languageCode = "en-us"
description = "An opinionated collection of R packages designed for data science."
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
# below is critical for non-authors to show up in article listing
preserveTaxonomyNames = true
# uncomment the next line to disable listing authors
# disableKinds = ["taxonomyTerm"]

[permalinks]
  blog = "blog/:year/:month/:slug/"

[taxonomies]
  author = "author"
  category = "categories"
  tag = "tags"
  format = "formats"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.tableOfContents]
    endLevel = 2
    ordered = false
    startLevel = 2
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    style = "pygments"
