[build]
  publish = "public"
  command = "hugo"

[build.environment]
  HUGO_VERSION = "0.80.0"

[context.deploy-preview.environment]
  command = "hugo --baseURL $DEPLOY_PRIME_URL"
  HUGO_BUILDFUTURE = "true"
  

[context.branch-preview.environment]
  command = "hugo --baseURL $DEPLOY_PRIME_URL"
  HUGO_BUILDFUTURE = "true"

